name: SpleefArena
main: darvin939.SpleefArena.SpleefArena
version: 0.5
description: SpleefArena v0.5
author: darvin939, darvin212@gmail.com
commands:
  spl:
    usage: /spl help
    description: Show help topic